config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#welcome"

  get '/about' => 'pages#about'
  get '/contacts' =>  'contacts#new'
    resources :contacts, only: [:new, :create]
  
  get '/projects' => 'projects#index'
    resources :projects

  get '/posts' => 'pages#posts'
    resources :posts

  #get 'pages/welcome'
  #get 'pages/about'
  #get 'pages/contact'
  #get 'pages/projects'
  #get 'pages/posts'
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,    :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "arturjanka@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
  
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
  def authenticate_admin!
    authenticate_user!
    
    unless current_user.admin?
      redirect_to root_path, alert: "You are not allowed to perform that operation."
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. I will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def about
  end

  def contacts
  end

  def projects
  end

  def posts
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy] 
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  
  def index
    @projects = Project.all.order("created_at desc")
  end
  def new
    @project = Project.new
  end
  def create 
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: "This project was successfully saved!"
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @project.update project_params
      redirect_to @project, notice: "This project was succesfully updated!"
    else
      render 'edit'
    end
  end
  
  def destroy
        @project.destroy
        redirect_to projects_path
  end
  
  private
  
  def find_project
    @project = Project.friendly.find(params[:id])
  end
  
  def project_params
    params.require(:project).permit(:title, :description, :link, :slug, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
            <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Hello, Send A Message to Me</h3>
<br>
<hr>
</div>

<div class="skinny_wrapper wrapper_padding">

    <%= form_for @contact do |f| %>
        <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, required: true, class: "form-control" %>
        </div><br>
        <div class="form-group">
            <%= f.label :email %><br>
            <%= f.email_field :email, required: true, class: "form-control"  %>
        </div><br>
        <div class="form-group">
            <%= f.label :message %><br>
            <%= f.text_area :message, as: :text, class: "form-control" %>
        </div><br>
        <div class="hidden">
                <%= f.label :nickname %><br>
                <%= f.text_field :nickname, hint: 'leave this field blank' %>
        </div>
        <div class="actions">
            <%= f.submit 'Send Message', class: "btn btn-primary" %>
        </div><br>
    <% end %>

</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
	 <h5 class="copyright">&copy;2016 Artur Janka</h5>
	 <nav>
	     <a href="https://www.facebook.com/artoriusXIII" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
	     <a href="https://www.linkedin.com/in/arturjanka?trk=nav_responsive_tab_profile_pic" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
	     <a href="https://www.github.com/ArtoriusXIII" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
	 </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Artur Janka</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Portfolio", projects_path %></li>
      <li><%= link_to "Resume", posts_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtusBayDesign</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg|  %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
            <button type="buton" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
  

    <%= yield %>
    <%= render 'layouts/footer'%>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="wrapper wrapper_padding clearfix">
    
    <div align="center">
      <h1>Welcome to Artur Janka portfolio</h1>
      <hr>
    </div>
    <div class="row">
        <div class="col-1 homepage_content">
            <div class="thumbnail">
                <img src="https://s3-eu-west-1.amazonaws.com/artustest/sesja_4.jpg">
            </div>
        </div>
            
        <div class="col-2 homepage_content">
            <p>The following are samples of my work. In each case I have had a significant (if not sole) development role. </p>
            <br>
            <p>The designs are the product of college works and individuals that I have worked with. </p>
            <p>I’m a new Rubyist user  as everything is much easier to create.
                I have a hunger for acquiring a new knowledge in every aspect and I find it interesting.</p>
            <p>To learn more about what I've done or if you have questions about a specific project please go to Contact form and email me.</p>
        </div>
    </div>
</div>

app/views/pages/posts.html.erb
<div class="row">
    <div class="col-xs-12 col-md-8">
        <address>
          <h2 strong>Artur Janka</h2><br>
          1 Glenard Avenue,<br>
          North Circular Road, Dublin 7<br>
          <abbr title="Phone">P:</abbr> +353894113471<br>
          <a href="mailto:#">arturjanka@gmail.com</a>
        </address>
    </div>
    <div class="col-xs-6 col-md-4">
            <div class="thumbnail">
                <img src="https://s3-eu-west-1.amazonaws.com/artustest/Artur_Janka5.jpg">
            </div>
    </div>

<br>
<h3 class>Profile</h3>
<hr>
<ul>
	<li>Higher Diploma in Science in Cloud Computing qualification from National College of Ireland.</li>
	<li>Construction Engineering graduate with 6 years’ experience in logistics and stock administration</li>
	<li>4 years’ experience in technical support and managing the stock inventory system in Lantec</li>
	<li>Recently upskilled in cloud computing producing an eCommerce and Marketplace website using Ubuntu environment with Ruby framework language</li>
</ul>
<br>
<h3 class>Languages:</h3>
<ul>
<li><p>English (fluent), Polish (native)</p></li>
</ul>
<br>

    <h3 class>Education:</h3>
    <hr>
    <div class="pull-left"><strong>2015-2016 </strong></div>
    <div class="pull-right"><strong>National College of Ireland</strong></div>
    <br>
    <br>
    <abbr title="Higher">Higher Diploma in Science in Cloud Computing</abbr><br>
    <div class="pull-left"><strong>Modules:</strong></div>
    <p="pull-right"> Introduction to Database, Software Development, Web Design,
    Computer Architecture Operating Systems and Networks, Cloud Application Development, 
    Project, Object Oriented Software Engineering, Cloud Computing in Business, Web Services and API Development, 
    Practical Operating System.</p>
    <div class="pull-left"><strong>Project:</strong></div>
    <p="pull-right">
    Designed and developed a HR website application using Ruby and Rails 
    Designed and developed Sandbox club for selling sport items and renting courts for teams to play inside 
    beach volleyball and soccer using Ruby on Rails. 
    Designed and developed a marketplace for customers to sell their stuff with ability to get a small fee 
    from every transaction using Ruby on Rails.</p>
    <br>
    <div class="pull-left"><strong>1996-2000</strong></div>
    <div class="pull-right"><strong>University of Technology in Opole, Poland</strong></div>
    <br>
    <br>
    <abbr title="Graduate">Graduate Diploma in Building and Engineering Structures</abbr><br>
    <p>Project designing the specification of a commercial warehouse.</p>



    <h3 class>Technical Skills:</h3>
    <hr>
    <div class="pull-left"><strong>Back end languages:</strong></div>
    <p="pull-right">Good knowledge of Java | Proficient with Ruby, Ruby on Rails.</p>
    <div class="pull-left"><strong>Front end web development:</strong></div>
     <p="pull-right">Proficient with JavaScript, jQuery, HTML, CSS, AngularJS, Bootstrap;</p>
    <div class="pull-left"><strong>Database:</strong></div>
    <p="pull-right">Used MySQL, SQLite, PostgreSQL; in college projects</p>
    <div class="pull-left"><strong>Portfolio:</strong></div>
    <p="pull-right">Built my own Git, GitHub, and Heroku;</p>
    <div class="pull-left"><strong>Accounting software:</strong></div>
    <p="pull-right">Experience using Sage Accounting Software Sage Quickpay, Sage L50; Excel 2003/2007 for Financial Modelling spreadsheets; SAP knowledge and experience;</p>
    <div class="pull-left"><strong>Operating Systems:</strong></div>
    <p="pull-right">Linux, Ubuntu, Windows</p>
    <br>


    <h3 class>Career History:</h3>
    <hr>
     <div class="pull-left"><strong>2017 :</strong></div>
    <div class="pull-right"><strong>Dublin</strong></div>
    <br><br>
    <abbr title="Career">Freelancer</abbr><br>
    <p>Responsible for create Website using Frond Back and Ruby on Rails framework.
    Design, build, and deploy a complete web applicastion with Ruby on Rails framework
    </p>
    
    
    <div class="pull-left"><strong>2011 – 2015 :</strong></div>
    <div class="pull-right"><strong>Lantec (UK) Ltd.</strong></div>
    <br><br>
    <abbr title="Career">Configuration Engineer (Technical Support)</abbr><br>
    <p>Responsible for contracts with AIB and Elavon | Managing a small team of technicians | Answering client queries by email / ticketing system in relation to contracts | Interacting with the engineering team to get software issues and bugs resolved |
    Calibrating and configuration of Credit/Laser card handheld terminals | Contribute ideas to the team to enhance customer satisfaction |
    Running Diagnostic checks on Modem and Ethernet connections to ensure application downloads | 
    Responsible for the refurbishment for all returned terminals, stock checks and stock movement on Lantec Inventory System & Lantec Management System.
    </p>
     		 
    <div class="pull-left"><strong>2Jul 2011 – Sep 2011</strong></div>
    <div class="pull-right"><strong>Eddie Stobart Ireland, Dublin Port</strong></div>
    <br><br>
    <abbr title="Career">Logistic administrato</abbr><br>
    <p>Maintaining of daily stock register system | Producing daily and weekly stock reconciliation reports | 
    Investigation of all operational discrepancies.
    </p>
    <div class="pull-left"><strong>Dec 2009 – May 2011</strong></div>
    <div class="pull-right"><strong>Arvato-Sonopress Digital Service Ireland Limited </strong></div>
    <br><br>
    <abbr title="Career">Logistic administration</abbr>
    <br>
    <p>Carrying out regular cycle counts/physical inventories | Printing and put away of all labels to the AWH or conventional warehouse | 
    Stock Management- Material Obsolescence – Purge Process | Printing from SAP daily shipping requirements, shipping off SAP “real time” | 
    Daily, weekly stock reconciliation, investigation of all breaks | Liaising with external counterparties in relation to inventory distribution process.
    </p>
    <div class="pull-left"><strong>Sep 2006 – May 2008</strong></div>
    <div class="pull-right"><strong>TDG Logistics</strong></div>
    <br><br>
    <abbr title="Career">Logistic officer</abbr><br>
    <br>
    <p>Stock controlling, checking deliveries and stock movements of Baileys & Diageo | Making out orders | 
    Recording returns to suppliers | Dispatching orders | Labelling logistic operations, goods in/out | 
    General administration | Stacking of orders.
    </p>
    
    <div class="pull-left"><strong>Jan 2005 – Sep 2006</strong></div>
    <div class="pull-right"><strong>EXEL </strong></div>
    <br><br>
    <abbr title="Career">Logistic officer</abbr><br>
    <br>
    <p>Administrative role | checked goods in/out and was responsible for stock inventory.</p>
    
    <div class="pull-left"><strong>2001 – 2004</strong></div>
    <div class="pull-right"><strong>CZB MERCUS Opole</strong></div>
    <br><br>
    <abbr title="Career">Sales Assistant Manager (building materials parts)</abbr><br>
    <br>  			
    
    <p>Handling Customer queries | Stock control | Dealing with suppliers and managing daily deliveries | Preparation of invoices
    </p>
    
    <div class="pull-left"><strong>1999 – 2001</strong></div>
    <div class="pull-right"><strong>Trans- Kaj, Opole</strong></div>
     <br><br>
    <abbr title="Career">Forwarder/Purchasing Assistant (Lafarge building materials) </abbr><br>
    <br>   			
    <p>Stock controller (Logistics and Forwarding office) | Processing and updating customer documentation | 
    Liaising on a daily basis with owners and contracted transport operators.
    </p>
    <div class="pull-left"><strong>1996-1999 </strong></div>
    <div class="pull-right"><strong>Motor Trade Parts, Opole </strong></div>
     <br><br>
    <abbr title="Career">Assistant Office Administrator (car parts brand)</abbr><br>
    <br>             		
    <p>Administering the office correspondence and e-mail | Sorting and posting outgoing mail | Filing | 
    Making up information kits and updating records | Monitoring stocks, stationery, printed material and supplies, 
    receives and checking deliveries | Dealing with enquiries and correspondence from clients | Contributing to the routine marketing, 
    dispatch information.
    </p>
    <div class="pull-left"><strong>1995-1996</strong></div>
    <div class="pull-right"><strong>SHELL Gas Station, Opole </strong></div>
    <br><br>
    <abbr title="Career">Sales Assistant Manager  r</abbr><br>
    <br>	
    <P>Maintaining and improving sales | ensuring best customer and client service | Inspecting received deliveries |
    Assisting leads and communications to all the staff.
    </p>
    <div class="pull-left"><strong>1994-1995</strong></div>
    <div class="pull-right"><strong>J.D Real Estate, Opole </strong></div>			 
     <br><br>
    <abbr title="Career">Real Estate Agent</abbr><br>
    <br>			
    <p>Valuation of properties | Assistance during sale process | Preparation of monthly management accounts | Customer service | 
    Marketing activities.
    </p>
    <br>

    <h3 class>Interests:</h3>
    <hr>
    <div class="pull-left"><strong>I.T.</strong></div>
    <p="pull-right">Take online courses on courser.org, codeacademy.com, skillfeed.com, tutsplus.com, Code School, teamtreehouse.com and codingforentrepreneurs.com on Ruby and Ruby on Rails.</p>
  	
    <div class="pull-left"><strong>Sport:</strong></div>
    <p="pull-right">Member of Dalkey volleyball team, participate in volleyball beach tournaments</p>
   
    <div class="pull-left"><strong>Archaeology:</strong></div>
    <p="pull-right">Interest in Viking history and the settlement of Dublin, also enjoy reading about history of Rome.</p>
    <br>
    <hr>
    <p="text-align center">References available upon request</p>
</div>

app/views/pages/projects.html.erb
<h1>Pages#projects</h1>
<p>Find me in app/views/pages/projects.html.erb</p>

app/views/pages/welcome.html.erb
<div id='main'>	
    <div class="jumbotron">
        <h1 class="text-left">Artur Janka </h1>
        <h2 class="text-left"> Web Developer</h2>
        <p><a class="btn btn-primary btn-lg" href="/projects" role="button">Learn more &raquo;</a></p>
    </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:multipart => true }) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div><br>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<div align="center">
    <h1 id="page_title">Stuff I have Built</h1>
    <hr>
    <div class="row clearfix">
        <% @projects.each do |project| %>
            <div class="col-md-4 project">
                <div class="thumbnail">
                    <%= link_to image_tag(project.image.url(:medium)), project %>
                    <div class="caption">
                        <p class="date"><%= project.created_at.strftime('%A %B %d') %></p>
                        <!--<h2><a href="#"><%= link_to project.title, project %></a></h2>-->
                    </div>
                </div>
              
                <hr>
            </div>
        <% end %>
    </div>
    <div class="button_wrapper">
        <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div align="center">
    <div id="project_wrapper" class="skinny_wrapper wrapper_padding">
        
        <h3><%= link_to @project.title, projects_path %></h3>
        <p><%= @project.created_at.strftime('%A %B %d')  %></p>
        <hr>
        <%= image_tag @project.image_url(:large) %>
        <hr>
        <p><%= @project.description %></p>
        <hr>
        <div class="button_wrapper">
            <a href="<%= @project.link %>" class="project_button" target="_blank" >Visit <%= @project.title %></a>
        </div>
        <!--<div class="button_wrapper">
            <%= link_to 'Back', projects_path, class: "project_button" %>
            
        </div>-->
            <%= link_to 'Edit project', edit_project_path(@project), class: "btn btn-primary" %>
            <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger" %>
            
         <hr>
        <br>  
    </div>
</div>